name: Build and Publish pac.pac

on:
  push:
    paths:
      - "src/pac.ts" # Запускать изменении src/pac.ts
      - ".github/workflows/build-and-publish.yaml" # Запускать изменении CI/CD файла

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: ✍️ Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Установка Node.js
      - name: 🥁 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      # Шаг 3: Установка зависимостей
      - name: 🧳 Install dependencies
        run: npm install

      # Шаг 4: Сборка проекта
      - name: ⚙️ Build project
        run: npm run build

      # Шаг 5: Публикация файла pac.pac в ветку build через gh-pages
      - name: 📖 Publish pac.pac to build branch
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -f -t false -d build -b build -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
